
pipeline {
  agent any

  environment {
    IMAGE_NAME = "balu9963/Balu_First_app"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Balu9963/devops-demo-project.git'
      }
    }

    stage('Build') {
      steps {
        sh 'cd demo-java-app && mvn clean package -DskipTests'
      }
    }

    stage('Docker Build') {
      steps {
        sh 'cd demo-java-app && docker build -t $IMAGE_NAME:latest .'
      }
    }

    stage('Docker Push') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
          echo $PASS | docker login -u $USER --password-stdin
          docker push $IMAGE_NAME:latest
          '''
        }
      }
    }

  }
}
