pipeline {
  agent any

  parameters {
    string(name: 'build_version', defaultValue: 'V1.0', description: 'Build version')
  }

  environment {
    DOCKER_IMAGE = "balu7777/demo-java-app:${build_version}"
    SONAR_URL    = "http://sonarqube:9000"   // change if NodePort
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/Balu9963/devops-demo-project.git'
      }
    }

    stage('Build') {
      steps {
        sh '''
          cd demo-java-app
          MAVEN_OPTS="-Xmx512m" mvn clean package -DskipTests
        '''
      }
    }

    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh '''
            cd demo-java-app
            MAVEN_OPTS="-Xmx512m" mvn sonar:sonar \
              -Dsonar.login=$SONAR_AUTH_TOKEN \
              -Dsonar.host.url=${SONAR_URL}
          '''
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          sh '''
            cd demo-java-app
            docker build -t ${DOCKER_IMAGE} .
          '''
          docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
            docker.image("${DOCKER_IMAGE}").push()
          }
        }
      }
    }

    stage('Update Deployment File') {
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh '''
            git config user.email "balun.9963@gmail.com"
            git config user.name "Balu"

            sed -i "s/tag: .*/tag: \\"${build_version}\\"/" helm/app/values.yaml

            if git diff --quiet; then
              echo "No changes to commit"
            else
              git add helm/app/values.yaml
              git commit -m "Update deployment image to ${build_version}"
              git push https://${GITHUB_TOKEN}@github.com/Balu9963/devops-demo-project.git HEAD:main
            fi
          '''
        }
      }
    }
  }
}
